pipeline:
  years: [2022, 2023]
  trimesters: [1, 2]
  output_dir: "data/processed"
  output_filename: "train.csv"
  transformations:
    - function: generar_jefe_trabaja
    - function: generar_conyuge_trabaja
    - function: generar_jefa_mujer
    - function: generar_hogar_monop
    - function: generar_ratio_ocupados_miembros
    - function: generar_nbi_subsistencia
    - function: generar_nbi_cobertura_previsional
    - function: generar_nbi_dificultad_laboral
    - function: generar_nbi_hacinamiento
    - function: generar_nbi_sanitaria
    - function: generar_nbi_tenencia
    - function: generar_nbi_trabajo_precario
    - function: generar_nbi_vivienda_precaria
    - function: generar_nbi_zona_vulnerable
